# Generated by Django 3.0.6 on 2020-05-20 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_tutorial_tutorialcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='created_by',
        ),
    ]
