# Generated by Django 3.0.6 on 2020-05-20 15:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
