# Generated by Django 3.0.6 on 2020-05-21 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_auto_20200520_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Django',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('slug', models.SlugField(max_length=100)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish_date',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='JavaScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('slug', models.SlugField(max_length=100)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish_date',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('slug', models.SlugField(max_length=100)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish_date',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='python',
            options={'ordering': ('-publish_date',)},
        ),
        migrations.AlterIndexTogether(
            name='python',
            index_together={('id', 'slug')},
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.DeleteModel(
            name='TutorialCategory',
        ),
    ]
